Server:
  Host: localhost
  Port: 6969
  SocketPort: 7089

Database:
  Host: remotemysql.com
  Port: a
  Name: a
  Username: a
  Password: a

SpaceServer:
  BucketName: a
  Endpoint: a
  Region: a
  AccessKey: a
  SecretKey: a