Server:
  Host: localhost
  Port: 6969
  SocketPort: 7089

Database:
  Host: remotemysql.com
  Port: 3306
  Name: Lm35wJUNJk
  Username: Lm35wJUNJk
  Password: oqI505OHlM

SpaceServer:
  BucketName: a
  Endpoint: a
  Region: a
  AccessKey: a
  SecretKey: a